### ISSUE TITLE
`@deprecated` breaks Enum classes on Python 3.12+

### ISSUE THREAD

**Issue by Borda** [Borda/pyDeprecate#101]
## Problem

Decorating an `Enum` class with `@deprecated(target=None, ...)` and then instantiating by value raises `TypeError` on Python 3.12+. Works fine on Python ≤3.11.

### Reproduction

```python
from enum import Enum
from deprecate import deprecated

@deprecated(target=None, deprecated_in="0.1", remove_in="0.2")
class Color(Enum):
    RED = "red"
    GREEN = "green"

Color.RED       # ✓ works
Color("red")    # ✗ TypeError: EnumType.__call__() got an unexpected keyword argument 'values'
```

### Cause

Python 3.12 changed what `inspect.signature()` returns for Enum classes:

```python
import inspect
from enum import Enum

class MyEnum(Enum):
    A = "a"

inspect.signature(MyEnum)
# Python ≤3.11: (value)    → POSITIONAL_OR_KEYWORD
# Python 3.12+: (*values)  → VAR_POSITIONAL
```

`_update_kwargs_with_args` inspects the source signature and converts positional args to kwargs. On 3.12 it sees `*values` and produces `kwargs = {"values": "red"}`. Then `source(**kwargs)` calls `Color(values="red")` which `EnumType.__call__()` does not accept.

### Real-world impact

The [supervision](https://github.com/roboflow/supervision) package decorates its `LMM` enum with `@deprecated(target=None, ...)`. Every call to `LMM("florence_2")` fails on Python 3.12.

## Test case

```python
import sys
from enum import Enum
import pytest
from deprecate import deprecated


@deprecated(target=None, deprecated_in="0.1", remove_in="0.2")
class DeprecatedEnum(Enum):
    ALPHA = "alpha"
    BETA = "beta"


@deprecated(target=None, deprecated_in="0.1", remove_in="0.2")
class DeprecatedIntEnum(Enum):
    ONE = 1
    TWO = 2


def test_enum_by_string_value():
    assert DeprecatedEnum("alpha") is DeprecatedEnum.ALPHA

def test_enum_by_int_value():
    assert DeprecatedIntEnum(1) is DeprecatedIntEnum.ONE

def test_enum_invalid_value_raises_valueerror():
    with pytest.raises(ValueError):
        DeprecatedEnum("nonexistent")

def test_enum_attribute_and_bracket_access():
    assert DeprecatedEnum.ALPHA.value == "alpha"
    assert DeprecatedEnum["ALPHA"] is DeprecatedEnum.ALPHA
```

### Environment

- **Broken:** Python 3.12, 3.13, 3.14
- **Works:** Python ≤3.11
- **pyDeprecate:** 0.4.0 (and older)
